-- complete_personal_task_fix.sql
-- This script completely resolves the personal task creation error
-- Run this entire script in your Supabase SQL Editor

-- STEP 1: Drop existing conflicting functions and tables (clean slate)
DROP FUNCTION IF EXISTS public.create_personal_task(text, date, time, text, integer);
DROP TABLE IF EXISTS public.personal_tasks CASCADE;

-- STEP 2: Create the personal_tasks table with proper structure
CREATE TABLE public.personal_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id text NOT NULL,
    appointment_date date NOT NULL,
    appointment_time time without time zone NOT NULL,
    duration_minutes integer NOT NULL CHECK (duration_minutes > 0),
    description text NOT NULL,
    status text DEFAULT 'scheduled' NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create indexes for better performance
CREATE INDEX idx_personal_tasks_staff_date ON public.personal_tasks(staff_id, appointment_date);
CREATE INDEX idx_personal_tasks_appointment_time ON public.personal_tasks(appointment_time);

-- Enable Row Level Security
ALTER TABLE public.personal_tasks ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Enable read access for authenticated users" ON public.personal_tasks
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Enable insert access for authenticated users" ON public.personal_tasks
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable update access for authenticated users" ON public.personal_tasks
    FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Enable delete access for authenticated users" ON public.personal_tasks
    FOR DELETE TO authenticated USING (true);

-- STEP 3: Create the RPC function with exact parameter names
CREATE OR REPLACE FUNCTION public.create_personal_task(
    staffId text,
    appointmentDate date,
    appointmentTime time,
    description text,
    durationMinutes integer DEFAULT 60
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    new_task_id bigint;
BEGIN
    -- Insert the personal task
    INSERT INTO public.personal_tasks (
        staff_id,
        appointment_date,
        appointment_time,
        duration_minutes,
        description
    ) VALUES (
        staffId,
        appointmentDate,
        appointmentTime,
        durationMinutes,
        description
    ) RETURNING id INTO new_task_id;
    
    RETURN new_task_id;
END;
$$;

-- STEP 4: Grant permissions
GRANT EXECUTE ON FUNCTION public.create_personal_task(text, date, time, text, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_personal_task(text, date, time, text, integer) TO service_role;

-- STEP 5: Also create a function that works with UUID staff_id (if needed)
CREATE OR REPLACE FUNCTION public.create_personal_task_uuid(
    staffId uuid,
    appointmentDate date,
    appointmentTime time,
    description text,
    durationMinutes integer DEFAULT 60
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    new_task_id bigint;
BEGIN
    INSERT INTO public.personal_tasks (
        staff_id,
        appointment_date,
        appointment_time,
        duration_minutes,
        description
    ) VALUES (
        staffId::text,
        appointmentDate,
        appointmentTime,
        durationMinutes,
        description
    ) RETURNING id INTO new_task_id;
    
    RETURN new_task_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_personal_task_uuid(uuid, date, time, text, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_personal_task_uuid(uuid, date, time, text, integer) TO service_role;

-- STEP 6: Create helper functions for retrieving personal tasks
CREATE OR REPLACE FUNCTION public.get_personal_tasks(
    staffId text,
    appointmentDate date
)
RETURNS TABLE(
    id bigint,
    staff_id text,
    appointment_date date,
    appointment_time time,
    duration_minutes integer,
    description text,
    status text,
    created_at timestamp with time zone
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        pt.id,
        pt.staff_id,
        pt.appointment_date,
        pt.appointment_time,
        pt.duration_minutes,
        pt.description,
        pt.status,
        pt.created_at
    FROM public.personal_tasks pt
    WHERE pt.staff_id = staffId 
    AND pt.appointment_date = appointmentDate
    ORDER BY pt.appointment_time;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_personal_tasks(text, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_personal_tasks(text, date) TO service_role;

-- STEP 7: Refresh the PostgREST schema
NOTIFY pgrst, 'reload schema';

-- STEP 8: Verify the function exists
SELECT 
    routine_name,
    routine_type,
    data_type
FROM information_schema.routines 
WHERE routine_name = 'create_personal_task' 
AND routine_schema = 'public';

-- Script complete! The personal task feature should now work.